export const hotCities = [
  { name: "上海", id: "sh", pinyin: "shanghai" },
  { name: "北京", id: "bj", pinyin: "beijing" },
  { name: "广州", id: "gz", pinyin: "guangzhou" },
  { name: "成都", id: "cd", pinyin: "chengdu" },
  { name: "深圳", id: "sz", pinyin: "shenzhen" },
  { name: "重庆", id: "cq", pinyin: "chongqing" },
  { name: "杭州", id: "hz", pinyin: "hangzhou" },
  { name: "西安", id: "xa", pinyin: "xian" },
]

export const cityData = [
  {
    letter: "A",
    list: [
      { name: "阿尔山", id: "aes", pinyin: "aershan" },
      { name: "阿克苏", id: "aks", pinyin: "akesu" },
      { name: "阿拉善右旗", id: "alsyq", pinyin: "alashanyouqi" },
      { name: "阿拉善左旗", id: "alszq", pinyin: "alashanzuoqi" },
      { name: "阿勒泰", id: "alt", pinyin: "aletai" },
      { name: "阿里", id: "al", pinyin: "ali" },
      { name: "安庆", id: "aq", pinyin: "anqing" },
      { name: "安顺", id: "as", pinyin: "anshun" },
      { name: "安阳", id: "ay", pinyin: "anyang" },
      { name: "安康", id: "ak", pinyin: "ankang" },
      { name: "鞍山", id: "anshan", pinyin: "anshan" },
      { name: "澳门", id: "am", pinyin: "aomen" },
    ],
  },
  {
    letter: "B",
    list: [
      { name: "北京", id: "bj", pinyin: "beijing" },
      { name: "保定", id: "bd", pinyin: "baoding" },
      { name: "包头", id: "bt", pinyin: "baotou" },
      { name: "北海", id: "bh", pinyin: "beihai" },
      { name: "宝鸡", id: "bji", pinyin: "baoji" },
      { name: "本溪", id: "bx", pinyin: "benxi" },
      { name: "蚌埠", id: "bb", pinyin: "bengbu" },
      { name: "亳州", id: "bozhou", pinyin: "bozhou" },
      { name: "白城", id: "bc", pinyin: "baicheng" },
      { name: "白山", id: "bs", pinyin: "baishan" },
      { name: "白银", id: "by", pinyin: "baiyin" },
      { name: "百色", id: "baise", pinyin: "baise" },
      { name: "巴中", id: "bz", pinyin: "bazhong" },
      { name: "滨州", id: "binzhou", pinyin: "binzhou" },
    ],
  },
  {
    letter: "C",
    list: [
      { name: "成都", id: "cd", pinyin: "chengdu" },
      { name: "重庆", id: "cq", pinyin: "chongqing" },
      { name: "长沙", id: "cs", pinyin: "changsha" },
      { name: "长春", id: "cc", pinyin: "changchun" },
      { name: "常州", id: "cz", pinyin: "changzhou" },
      { name: "沧州", id: "cangzhou", pinyin: "cangzhou" },
      { name: "常德", id: "changde", pinyin: "changde" },
      { name: "郴州", id: "chenzhou", pinyin: "chenzhou" },
      { name: "赤峰", id: "cf", pinyin: "chifeng" },
      { name: "池州", id: "chizhou", pinyin: "chizhou" },
      { name: "承德", id: "chengde", pinyin: "chengde" },
      { name: "滁州", id: "chuzhou", pinyin: "chuzhou" },
      { name: "楚雄", id: "cx", pinyin: "chuxiong" },
      { name: "朝阳", id: "cy", pinyin: "chaoyang" },
      { name: "潮州", id: "chaozhou", pinyin: "chaozhou" },
    ],
  },
  {
    letter: "D",
    list: [
      { name: "大连", id: "dl", pinyin: "dalian" },
      { name: "东莞", id: "dg", pinyin: "dongguan" },
      { name: "大理", id: "dali", pinyin: "dali" },
      { name: "丹东", id: "dd", pinyin: "dandong" },
      { name: "大庆", id: "dq", pinyin: "daqing" },
      { name: "大同", id: "dt", pinyin: "datong" },
      { name: "德阳", id: "dy", pinyin: "deyang" },
      { name: "德州", id: "dz", pinyin: "dezhou" },
      { name: "东营", id: "dongying", pinyin: "dongying" },
      { name: "达州", id: "dazhou", pinyin: "dazhou" },
      { name: "定西", id: "dx", pinyin: "dingxi" },
      { name: "迪庆", id: "diqing", pinyin: "diqing" },
      { name: "儋州", id: "danzhou", pinyin: "danzhou" },
    ],
  },
  {
    letter: "E",
    list: [
      { name: "鄂尔多斯", id: "eeds", pinyin: "eerduosi" },
      { name: "恩施", id: "es", pinyin: "enshi" },
      { name: "鄂州", id: "ezhou", pinyin: "ezhou" },
    ],
  },
  {
    letter: "F",
    list: [
      { name: "福州", id: "fz", pinyin: "fuzhou" },
      { name: "佛山", id: "fs", pinyin: "foshan" },
      { name: "抚顺", id: "fushun", pinyin: "fushun" },
      { name: "阜阳", id: "fy", pinyin: "fuyang" },
      { name: "抚州", id: "fuzhou2", pinyin: "fuzhou" },
      { name: "防城港", id: "fcg", pinyin: "fangchenggang" },
      { name: "阜新", id: "fx", pinyin: "fuxin" },
    ],
  },
  {
    letter: "G",
    list: [
      { name: "广州", id: "gz", pinyin: "guangzhou" },
      { name: "桂林", id: "gl", pinyin: "guilin" },
      { name: "贵阳", id: "gy", pinyin: "guiyang" },
      { name: "赣州", id: "ganzhou", pinyin: "ganzhou" },
      { name: "广元", id: "guangyuan", pinyin: "guangyuan" },
      { name: "广安", id: "ga", pinyin: "guangan" },
      { name: "贵港", id: "gg", pinyin: "guigang" },
      { name: "固原", id: "guyuan", pinyin: "guyuan" },
      { name: "甘南", id: "gn", pinyin: "gannan" },
      { name: "甘孜", id: "ganzi", pinyin: "ganzi" },
    ],
  },
  {
    letter: "H",
    list: [
      { name: "杭州", id: "hz", pinyin: "hangzhou" },
      { name: "哈尔滨", id: "heb", pinyin: "haerbin" },
      { name: "海口", id: "hk", pinyin: "haikou" },
      { name: "合肥", id: "hf", pinyin: "hefei" },
      { name: "呼和浩特", id: "hhht", pinyin: "huhehaote" },
      { name: "惠州", id: "huizhou", pinyin: "huizhou" },
      { name: "衡阳", id: "hengyang", pinyin: "hengyang" },
      { name: "邯郸", id: "handan", pinyin: "handan" },
      { name: "淮安", id: "ha", pinyin: "huaian" },
      { name: "淮北", id: "hb", pinyin: "huaibei" },
      { name: "淮南", id: "hn", pinyin: "huainan" },
      { name: "黄冈", id: "hg", pinyin: "huanggang" },
      { name: "黄山", id: "hs", pinyin: "huangshan" },
      { name: "黄石", id: "huangshi", pinyin: "huangshi" },
      { name: "湖州", id: "huzhou", pinyin: "huzhou" },
      { name: "菏泽", id: "heze", pinyin: "heze" },
      { name: "贺州", id: "hezhou", pinyin: "hezhou" },
      { name: "红河", id: "hh", pinyin: "honghe" },
      { name: "呼伦贝尔", id: "hlbe", pinyin: "hulunbeier" },
      { name: "葫芦岛", id: "hld", pinyin: "huludao" },
      { name: "汉中", id: "hanzhong", pinyin: "hanzhong" },
      { name: "鹤壁", id: "hebi", pinyin: "hebi" },
      { name: "鹤岗", id: "hegang", pinyin: "hegang" },
      { name: "河源", id: "heyuan", pinyin: "heyuan" },
      { name: "河池", id: "hechi", pinyin: "hechi" },
      { name: "黑河", id: "heihe", pinyin: "heihe" },
      { name: "衡水", id: "hengshui", pinyin: "hengshui" },
      { name: "怀化", id: "hh2", pinyin: "huaihua" },
      { name: "香港", id: "xianggang", pinyin: "xianggang" },
    ],
  },
  {
    letter: "I",
    list: [],
  },
  {
    letter: "J",
    list: [
      { name: "济南", id: "jn", pinyin: "jinan" },
      { name: "嘉兴", id: "jx", pinyin: "jiaxing" },
      { name: "吉林", id: "jl", pinyin: "jilin" },
      { name: "九江", id: "jj", pinyin: "jiujiang" },
      { name: "金华", id: "jh", pinyin: "jinhua" },
      { name: "济宁", id: "jining", pinyin: "jining" },
      { name: "江门", id: "jm", pinyin: "jiangmen" },
      { name: "焦作", id: "jz", pinyin: "jiaozuo" },
      { name: "晋城", id: "jc", pinyin: "jincheng" },
      { name: "晋中", id: "jz2", pinyin: "jinzhong" },
      { name: "锦州", id: "jinzhou", pinyin: "jinzhou" },
      { name: "荆门", id: "jingmen", pinyin: "jingmen" },
      { name: "荆州", id: "jingzhou", pinyin: "jingzhou" },
      { name: "景德镇", id: "jdz", pinyin: "jingdezhen" },
      { name: "揭阳", id: "jy", pinyin: "jieyang" },
      { name: "吉安", id: "ja", pinyin: "jian" },
      { name: "佳木斯", id: "jms", pinyin: "jiamusi" },
      { name: "鸡西", id: "jixi", pinyin: "jixi" },
      { name: "酒泉", id: "jq", pinyin: "jiuquan" },
    ],
  },
  {
    letter: "K",
    list: [
      { name: "昆明", id: "km", pinyin: "kunming" },
      { name: "开封", id: "kf", pinyin: "kaifeng" },
      { name: "喀什", id: "ks", pinyin: "kashi" },
      { name: "克拉玛依", id: "klmy", pinyin: "kelamayi" },
    ],
  },
  {
    letter: "L",
    list: [
      { name: "拉萨", id: "ls", pinyin: "lasa" },
      { name: "兰州", id: "lz", pinyin: "lanzhou" },
      { name: "丽江", id: "lj", pinyin: "lijiang" },
      { name: "洛阳", id: "ly", pinyin: "luoyang" },
      { name: "柳州", id: "liuzhou", pinyin: "liuzhou" },
      { name: "泸州", id: "luzhou", pinyin: "luzhou" },
      { name: "临沂", id: "linyi", pinyin: "linyi" },
      { name: "连云港", id: "lyg", pinyin: "lianyungang" },
      { name: "廊坊", id: "lf", pinyin: "langfang" },
      { name: "乐山", id: "leshan", pinyin: "leshan" },
      { name: "聊城", id: "lc", pinyin: "liaocheng" },
      { name: "辽阳", id: "liaoyang", pinyin: "liaoyang" },
      { name: "辽源", id: "liaoyuan", pinyin: "liaoyuan" },
      { name: "临汾", id: "linfen", pinyin: "linfen" },
      { name: "临夏", id: "lx", pinyin: "linxia" },
      { name: "丽水", id: "lishui", pinyin: "lishui" },
      { name: "六安", id: "la", pinyin: "liuan" },
      { name: "六盘水", id: "lps", pinyin: "liupanshui" },
      { name: "龙岩", id: "longyan", pinyin: "longyan" },
      { name: "娄底", id: "ld", pinyin: "loudi" },
      { name: "吕梁", id: "lvliang", pinyin: "lvliang" },
      { name: "来宾", id: "lb", pinyin: "laibin" },
      { name: "莱芜", id: "lw", pinyin: "laiwu" },
      { name: "陇南", id: "ln", pinyin: "longnan" },
      { name: "漯河", id: "lh", pinyin: "luohe" },
    ],
  },
  {
    letter: "M",
    list: [
      { name: "绵阳", id: "my", pinyin: "mianyang" },
      { name: "牡丹江", id: "mdj", pinyin: "mudanjiang" },
      { name: "马鞍山", id: "mas", pinyin: "maanshan" },
      { name: "茂名", id: "mm", pinyin: "maoming" },
      { name: "眉山", id: "ms", pinyin: "meishan" },
      { name: "梅州", id: "mz", pinyin: "meizhou" },
    ],
  },
  {
    letter: "N",
    list: [
      { name: "南京", id: "nj", pinyin: "nanjing" },
      { name: "南昌", id: "nc", pinyin: "nanchang" },
      { name: "南宁", id: "nn", pinyin: "nanning" },
      { name: "宁波", id: "nb", pinyin: "ningbo" },
      { name: "南通", id: "nt", pinyin: "nantong" },
      { name: "南充", id: "nanchong", pinyin: "nanchong" },
      { name: "南阳", id: "ny", pinyin: "nanyang" },
      { name: "南平", id: "np", pinyin: "nanping" },
      { name: "内江", id: "nj2", pinyin: "neijiang" },
      { name: "宁德", id: "nd", pinyin: "ningde" },
      { name: "怒江", id: "nujiang", pinyin: "nujiang" },
    ],
  },
  {
    letter: "O",
    list: [],
  },
  {
    letter: "P",
    list: [
      { name: "盘锦", id: "pj", pinyin: "panjin" },
      { name: "攀枝花", id: "pzh", pinyin: "panzhihua" },
      { name: "平顶山", id: "pds", pinyin: "pingdingshan" },
      { name: "萍乡", id: "px", pinyin: "pingxiang" },
      { name: "平凉", id: "pl", pinyin: "pingliang" },
      { name: "莆田", id: "pt", pinyin: "putian" },
      { name: "濮阳", id: "py", pinyin: "puyang" },
      { name: "普洱", id: "pe", pinyin: "puer" },
    ],
  },
  {
    letter: "Q",
    list: [
      { name: "青岛", id: "qd", pinyin: "qingdao" },
      { name: "泉州", id: "qz", pinyin: "quanzhou" },
      { name: "秦皇岛", id: "qhd", pinyin: "qinhuangdao" },
      { name: "齐齐哈尔", id: "qqhe", pinyin: "qiqihaer" },
      { name: "衢州", id: "quzhou", pinyin: "quzhou" },
      { name: "清远", id: "qy", pinyin: "qingyuan" },
      { name: "庆阳", id: "qingyang", pinyin: "qingyang" },
      { name: "曲靖", id: "qj", pinyin: "qujing" },
      { name: "钦州", id: "qinzhou", pinyin: "qinzhou" },
      { name: "黔南", id: "qn", pinyin: "qiannan" },
      { name: "黔东南", id: "qdn", pinyin: "qiandongnan" },
      { name: "黔西南", id: "qxn", pinyin: "qianxinan" },
    ],
  },
  {
    letter: "R",
    list: [
      { name: "日照", id: "rz", pinyin: "rizhao" },
      { name: "日喀则", id: "rkz", pinyin: "rikaze" },
    ],
  },
  {
    letter: "S",
    list: [
      { name: "上海", id: "sh", pinyin: "shanghai" },
      { name: "深圳", id: "sz", pinyin: "shenzhen" },
      { name: "沈阳", id: "sy", pinyin: "shenyang" },
      { name: "石家庄", id: "sjz", pinyin: "shijiazhuang" },
      { name: "苏州", id: "suzhou", pinyin: "suzhou" },
      { name: "三亚", id: "sanya", pinyin: "sanya" },
      { name: "绍兴", id: "sx", pinyin: "shaoxing" },
      { name: "汕头", id: "st", pinyin: "shantou" },
      { name: "汕尾", id: "sw", pinyin: "shanwei" },
      { name: "韶关", id: "sg", pinyin: "shaoguan" },
      { name: "邵阳", id: "shaoyang", pinyin: "shaoyang" },
      { name: "十堰", id: "shiyan", pinyin: "shiyan" },
      { name: "遂宁", id: "sn", pinyin: "suining" },
      { name: "随州", id: "suizhou", pinyin: "suizhou" },
      { name: "宿迁", id: "sq", pinyin: "suqian" },
      { name: "宿州", id: "suzhouan", pinyin: "suzhou" },
      { name: "三门峡", id: "smx", pinyin: "sanmenxia" },
      { name: "三明", id: "sm", pinyin: "sanming" },
      { name: "商丘", id: "shangqiu", pinyin: "shangqiu" },
      { name: "商洛", id: "shangluo", pinyin: "shangluo" },
      { name: "双鸭山", id: "sys", pinyin: "shuangyashan" },
      { name: "朔州", id: "shuozhou", pinyin: "shuozhou" },
      { name: "四平", id: "sp", pinyin: "siping" },
      { name: "松原", id: "songyuan", pinyin: "songyuan" },
      { name: "绥化", id: "suihua", pinyin: "suihua" },
    ],
  },
  {
    letter: "T",
    list: [
      { name: "天津", id: "tj", pinyin: "tianjin" },
      { name: "太原", id: "ty", pinyin: "taiyuan" },
      { name: "唐山", id: "ts", pinyin: "tangshan" },
      { name: "台州", id: "tz", pinyin: "taizhou" },
      { name: "泰州", id: "taizhou", pinyin: "taizhou" },
      { name: "泰安", id: "ta", pinyin: "taian" },
      { name: "通辽", id: "tl", pinyin: "tongliao" },
      { name: "通化", id: "th", pinyin: "tonghua" },
      { name: "铜陵", id: "tongling", pinyin: "tongling" },
      { name: "铜川", id: "tc", pinyin: "tongchuan" },
      { name: "铜仁", id: "tr", pinyin: "tongren" },
      { name: "天水", id: "tianshui", pinyin: "tianshui" },
      { name: "吐鲁番", id: "tlf", pinyin: "tulufan" },
    ],
  },
  {
    letter: "U",
    list: [],
  },
  {
    letter: "V",
    list: [],
  },
  {
    letter: "W",
    list: [
      { name: "武汉", id: "wh", pinyin: "wuhan" },
      { name: "无锡", id: "wx", pinyin: "wuxi" },
      { name: "温州", id: "wz", pinyin: "wenzhou" },
      { name: "乌鲁木齐", id: "wlmq", pinyin: "wulumuqi" },
      { name: "芜湖", id: "wuhu", pinyin: "wuhu" },
      { name: "威海", id: "weihai", pinyin: "weihai" },
      { name: "潍坊", id: "wf", pinyin: "weifang" },
      { name: "渭南", id: "wn", pinyin: "weinan" },
      { name: "文山", id: "ws", pinyin: "wenshan" },
      { name: "梧州", id: "wuzhou", pinyin: "wuzhou" },
      { name: "乌海", id: "wuhai", pinyin: "wuhai" },
      { name: "乌兰察布", id: "wlcb", pinyin: "wulanchabu" },
      { name: "吴忠", id: "wz2", pinyin: "wuzhong" },
      { name: "五指山", id: "wzs", pinyin: "wuzhishan" },
    ],
  },
  {
    letter: "X",
    list: [
      { name: "西安", id: "xa", pinyin: "xian" },
      { name: "厦门", id: "xm", pinyin: "xiamen" },
      { name: "西宁", id: "xn", pinyin: "xining" },
      { name: "徐州", id: "xz", pinyin: "xuzhou" },
      { name: "咸阳", id: "xy", pinyin: "xianyang" },
      { name: "襄阳", id: "xiangyang", pinyin: "xiangyang" },
      { name: "湘潭", id: "xt", pinyin: "xiangtan" },
      { name: "湘西", id: "xiangxi", pinyin: "xiangxi" },
      { name: "新乡", id: "xx", pinyin: "xinxiang" },
      { name: "信阳", id: "xinyang", pinyin: "xinyang" },
      { name: "许昌", id: "xc", pinyin: "xuchang" },
      { name: "宣城", id: "xuancheng", pinyin: "xuancheng" },
      { name: "邢台", id: "xingtai", pinyin: "xingtai" },
      { name: "忻州", id: "xinzhou", pinyin: "xinzhou" },
      { name: "兴安盟", id: "xam", pinyin: "xinganmeng" },
      { name: "锡林郭勒盟", id: "xlglm", pinyin: "xilinguolemeng" },
      { name: "西双版纳", id: "xsbn", pinyin: "xishuangbanna" },
    ],
  },
  {
    letter: "Y",
    list: [
      { name: "烟台", id: "yt", pinyin: "yantai" },
      { name: "银川", id: "yc", pinyin: "yinchuan" },
      { name: "扬州", id: "yz", pinyin: "yangzhou" },
      { name: "宜昌", id: "yichang", pinyin: "yichang" },
      { name: "宜宾", id: "yb", pinyin: "yibin" },
      { name: "宜春", id: "yichun", pinyin: "yichun" },
      { name: "伊春", id: "yc2", pinyin: "yichun" },
      { name: "益阳", id: "yiyang", pinyin: "yiyang" },
      { name: "营口", id: "yk", pinyin: "yingkou" },
      { name: "永州", id: "yongzhou", pinyin: "yongzhou" },
      { name: "岳阳", id: "yueyang", pinyin: "yueyang" },
      { name: "运城", id: "yuncheng", pinyin: "yuncheng" },
      { name: "榆林", id: "yl", pinyin: "yulin" },
      { name: "玉林", id: "yulin2", pinyin: "yulin" },
      { name: "玉溪", id: "yx", pinyin: "yuxi" },
      { name: "延安", id: "ya", pinyin: "yanan" },
      { name: "延边", id: "yanbian", pinyin: "yanbian" },
      { name: "盐城", id: "yancheng", pinyin: "yancheng" },
      { name: "阳江", id: "yj", pinyin: "yangjiang" },
      { name: "阳泉", id: "yq", pinyin: "yangquan" },
      { name: "雅安", id: "yaan", pinyin: "yaan" },
      { name: "云浮", id: "yf", pinyin: "yunfu" },
      { name: "鹰潭", id: "yingtan", pinyin: "yingtan" },
      { name: "伊犁", id: "yili", pinyin: "yili" },
    ],
  },
  {
    letter: "Z",
    list: [
      { name: "郑州", id: "zz", pinyin: "zhengzhou" },
      { name: "珠海", id: "zh", pinyin: "zhuhai" },
      { name: "中山", id: "zs", pinyin: "zhongshan" },
      { name: "中卫", id: "zw", pinyin: "zhongwei" },
      { name: "周口", id: "zk", pinyin: "zhoukou" },
      { name: "舟山", id: "zhoushan", pinyin: "zhoushan" },
      { name: "株洲", id: "zhuzhou", pinyin: "zhuzhou" },
      { name: "淄博", id: "zb", pinyin: "zibo" },
      { name: "自贡", id: "zg", pinyin: "zigong" },
      { name: "资阳", id: "zy", pinyin: "ziyang" },
      { name: "遵义", id: "zunyi", pinyin: "zunyi" },
      { name: "漳州", id: "zhangzhou", pinyin: "zhangzhou" },
      { name: "湛江", id: "zj", pinyin: "zhanjiang" },
      { name: "张家界", id: "zjj", pinyin: "zhangjiajie" },
      { name: "张家口", id: "zjk", pinyin: "zhangjiakou" },
      { name: "张掖", id: "zhangye", pinyin: "zhangye" },
      { name: "肇庆", id: "zq", pinyin: "zhaoqing" },
      { name: "镇江", id: "zhenjiang", pinyin: "zhenjiang" },
      { name: "驻马店", id: "zmd", pinyin: "zhumadian" },
      { name: "昭通", id: "zt", pinyin: "zhaotong" },
    ],
  },
]
